### ISSUE TITLE
TsComponent为何无法挂载？

### ISSUE THREAD

**Issue by lovoror** [throw-out/puerts-unity-kit#13]
<img width="399" alt="image" src="https://github.com/throw-out/puerts-unity-kit/assets/747608/7243648e-6d52-4411-b5de-a0d57713cb51">

这里找不到class

**Comment by throw-out** [comment]
编译是否报错?

**Comment by lovoror** [comment]
没报错，应该是partial关键字导致的，一个项目不能有2个同名的TsComponet.cs
把 01_TsComponent/CustomTypes/Runtime下的TsComponent改名为TsComponet.partial.cs就可以了。

**Comment by throw-out** [comment]
请问你使用的是什么版本的Unity? 

一般情况下Unity会将partial合并编译且可正常运行, 请确认以下文件是否存在:
01_TsComponent/CustomTypes/Runtime/puerts.unity.kit.xor.asmref

如其不存在, 则此处的TsComponet.cs无法合并进puerts.unity.kit.xor程序集, 自定义数据字段将无法生效.

**Comment by lovoror** [comment]
<img width="432" alt="image" src="https://github.com/throw-out/puerts-unity-kit/assets/747608/bed2c68a-e776-4351-9090-6983a8422d79">
2022.2.2f1版本
