### ISSUE TITLE
TSLoader question

### ISSUE THREAD

**Issue by raad-genies** [throw-out/puerts-unity-kit#14]
Hello again!

I am getting back into setting up this package and part of my research is https://github.com/zombieyang/puerts-ts-loader the nice thing about the ts loader package is it allows to deal with modules in a more unity way which is preferable. I was wondering if it would work out of the box since I know for TsComponent searching for modules is based on settings and a background thread worker.

**Comment by throw-out** [comment]
Sorry for taking so long to reply.

--------------------

Please forgive my lack of English, the following content is from the robot.

--------------------

The TsComponent is divided into two modules: Editor and Runtime. The Editor module is responsible for initiating the TypeScript analysis service (similar to what an IDE does) and adding the necessary decorator annotations. It should function properly using TSLoader.

In the subsequent Runtime mode, all that is needed is to first execute ExecuteModule(scriptContent), and then TsComponent can execute normal code using the decorator annotations.

--------------------

TsComponent分为Editor和Runtime模块, Editor模块负责启动typescript分析服务(就像ide做的那样)并添加必要的Decorator标注. 使用TSLoader它也应该可以正常运行.

在之后的Runtime模式中, 只需要先进行ExecuteModule(scriptContent), 然后TsComopoent就能通过Decorator标注来执行正常的代码.

**Comment by raad-genies** [comment]
> Sorry for taking so long to reply.
> 
> Please forgive my lack of English, the following content is from the robot.
> 
> The TsComponent is divided into two modules: Editor and Runtime. The Editor module is responsible for initiating the TypeScript analysis service (similar to what an IDE does) and adding the necessary decorator annotations. It should function properly using TSLoader.
> 
> In the subsequent Runtime mode, all that is needed is to first execute ExecuteModule(scriptContent), and then TsComponent can execute normal code using the decorator annotations.
> 
> TsComponent分为Editor和Runtime模块, Editor模块负责启动typescript分析服务(就像ide做的那样)并添加必要的Decorator标注. 使用TSLoader它也应该可以正常运行.
> 
> 在之后的Runtime模式中, 只需要先进行ExecuteModule(scriptContent), 然后TsComopoent就能通过Decorator标注来执行正常的代码.

no worries! thank you for replying, I think using `TSLoader` would be nice to allow a more natural unity UX, by modifying `TSComponent` to work with `TSLoader` you can realize the drag and drop functionality for `TS` Scripts and allow developers to create `TSComponent` in `Assets/`. `TSLoader` also already handles paths for in editor for any TS script as long as its relative to a `.tsconfig`, I can try to edit and submit a PR but something to consider as an improvement as working outside of `Assets` isn't natural to the unity way!

Thank you 👍

**Comment by throw-out** [comment]
The primary consideration is the `node_modules` directory. If it is created within the Assets directory, Unity will generate a large number of unnecessary redundant .meta files. This is not ideal for disk management. Therefore, when choosing the TypeScript development directory, it is placed outside the Assets directory.

-----

最主要的考虑是`node_modules`如果创建在Assets目录下, Unity将会生成大量无用冗余的.meta文件, 这对磁盘管理来说不是一个好消息, 因此在选择typescript开发目录时将其放在了Assets目录之外

**Comment by raad-genies** [comment]
I see, that would definitely be an inconvenience, I think I need to understand the inner-working of the plugin more, but maybe there's a way to allow both workflows? The TSLoader plugin does seem to include a node module loader based on the examples here it seems like that would allow loading node_modules from outside of the project, https://github.com/zombieyang/puerts-ts-loader?tab=readme-ov-file#detailed-examples I do see that you contributed to that project so you probably understand the limitations way better!

**Comment by throw-out** [comment]
> I see, that would definitely be an inconvenience, I think I need to understand the inner-working of the plugin more, but maybe there's a way to allow both workflows? The TSLoader plugin does seem to include a node module loader based on the examples here it seems like that would allow loading node_modules from outside of the project, https://github.com/zombieyang/puerts-ts-loader?tab=readme-ov-file#detailed-examples I do see that you contributed to that project so you probably understand the limitations way better!

It looks great. I have never considered developing multiple TypeScript projects in conjunction with each other, but it appears to be a feasible and suitable development approach.

-----------

它看起来似乎很棒.
我从未想过多个typescript项目相互搭配开发, 但它看起来是可行的且合适的开发方式.

**Comment by raad-genies** [comment]
I agree! having TSComponent accept modules as a drag and drop would be great and it would also reduce the amount of work needed on the thread. Since TSLoader handles resolving/collecting all paths from all projects, and for node_modules you can add a loader for them outside of unity project for better structure, this creates a very nice kit for unity where it feels very familiar without having to deal with 2 separate projects (unity/ts) so less context switching. Thank you for the conversation! I don't think its a super necessary feature as TSLoader can be implemented separately to manage chaining but would be a very nice to have if you have time, I'm new to TS/JS so still doing a lot of investigation but once I'm done and understand the ecosystem better I'll try to submit a PR

**Comment by throw-out** [comment]
Due to inactivity, this issue has been closed. You can reopen it later.
