### ISSUE TITLE
Custom Types

### ISSUE THREAD

**Issue by raad-genies** [throw-out/puerts-unity-kit#15]
How can I render custom types created on Ts Side? examples only show how to render custom types created on C# side.

**Comment by throw-out** [comment]
Not supporting the serialization of TypeScript-side data types. Complete TypeScript type serialization support would require preserving prototype chain information, which is a complex and performance-intensive feature.

**Comment by throw-out** [comment]
Due to inactivity, this issue has been closed. You can reopen it later.
