### ISSUE TITLE
Behaviour is missing in Samples/01_TsComponent

### ISSUE THREAD

**Issue by Ricardo2001ZG** [throw-out/puerts-unity-kit#18]
![17243225361269](https://github.com/user-attachments/assets/72c3eb1e-9558-4ae0-9e44-341c7ef2f0fe)

请问是否缺少了类似 Sample_01.cs 的 cs 脚本进行 ts 脚本调用？

运行 01 场景时提示找不到引用，对照其他样例场景查看，其他场景有 Sample_xx.cs 类的脚本进行 app.Load，但 01 场景没有

**Comment by throw-out** [comment]
Samples/01_TsComponent是TsComponent组件的演示场景, 无需额外的Sample_xx.cs 类调用逻辑.

你这里的问题看起来像是TsComponent.cs的引用丢失造成的, 请检查以下文件是否存在或被更改:
- Assets/XOR/Runtime/Src/Components/TsComponent.cs
- Assets/XOR/Runtime/Src/Components/TsComponent.cs.meta

**Comment by Ricardo2001ZG** [comment]
> Samples/01_TsComponent是TsComponent组件的演示场景, 无需额外的Sample_xx.cs 类调用逻辑.
> 
> 你这里的问题看起来像是TsComponent.cs的引用丢失造成的, 请检查以下文件是否存在或被更改:
> 
> * Assets/XOR/Runtime/Src/Components/TsComponent.cs
> * Assets/XOR/Runtime/Src/Components/TsComponent.cs.meta
> 
> 请特别注意TsComponent.cs.meta文件中的guid是否被更改: ![image](https://private-user-images.githubusercontent.com/45587825/360413584-c942c046-7c98-4fe8-a3c4-d8390224433e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjc4NDcsIm5iZiI6MTcyNDMyNzU0NywicGF0aCI6Ii80NTU4NzgyNS8zNjA0MTM1ODQtYzk0MmMwNDYtN2M5OC00ZmU4LWEzYzQtZDgzOTAyMjQ0MzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExNTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGNiZmUyYzA0ZGE0OTM2NDdlZGJiMTgyN2YyYmE1MDFkM2ZmYzlhZDhmZjFkMDg5MGZiM2Y2MGU5NGI0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wAyESXqEwPFdu0q3kGz51DqV8qqmGZLvCvDydBwANME)

![20240822195215](https://github.com/user-attachments/assets/fa6b5640-21bc-47e5-b5b8-5e9c4a3fee7a)

![1724327842750](https://github.com/user-attachments/assets/575fd31a-1415-4171-90c4-3b5b695d5fa1)

您好，我检查了 TsComponent 本身的 guid，并且查了 Sample01 的场景文件引用，现在是一致的。

但是我对这个项目进行了版本变更，现在是 2022.3.20f1c1，面板没有显示与 README 里面相同的模块和引用等信息，且日志只显示前文的 Warning，没有报 Error，不知是不是需要我对部分代码手动升级做兼容性处理？

**Comment by throw-out** [comment]
我检查了一下线上仓库内的场景文件`Assets/Samples/01_TsComponent/Scene.unity`, 并未发现问题(如下图). 
![image](https://github.com/user-attachments/assets/f095bc3e-4612-468d-a29d-5211a5df7512)

您遇到的问题, 可能是由于未知原因(例如guid冲突)导致TsComponent.cs的guid被强制修改/修正, 从而丢失了脚本引用. 之后再遇到此类问题, 你可以尝试手动修复.

前文的`Behaviour is missing`是Unity在引用丢失时的默认输出信息, 确实不会抛出错误

**Comment by Ricardo2001ZG** [comment]
> 我检查了一下线上仓库内的场景文件`Assets/Samples/01_TsComponent/Scene.unity`, 并未发现问题(如下图). ![image](https://private-user-images.githubusercontent.com/45587825/360421551-f095bc3e-4612-468d-a29d-5211a5df7512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzAwNzYsIm5iZiI6MTcyNDMyOTc3NiwicGF0aCI6Ii80NTU4NzgyNS8zNjA0MjE1NTEtZjA5NWJjM2UtNDYxMi00NjhkLWEyOWQtNTIxMWE1ZGY3NTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEyMjkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMmMzZDc0MGNjM2Q5YzhiNzhmODFlNGQ5NDk4MTVlMmMwMWYzMmFlZjBjMThhMDY3Y2NlZDc2ZDg0MTllNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r-hCYiZ3wYlLENdzRUUv_i8EPRtq6ZNPwEVFYKTEqsI)
> 
> 您遇到的问题, 可能是由于未知原因(例如guid冲突)导致TsComponent.cs的guid被强制修改/修正, 从而丢失了脚本引用. 之后再遇到此类问题, 你可以尝试手动修复.
> 
> 前文的`Behaviour is missing`是Unity在引用丢失时的默认输出信息, 确实不会抛出错误

好的谢谢，我去本地单步调试跟一下这个 guid 的引用，看是哪里导致的引用丢失

**Comment by Ricardo2001ZG** [comment]
请问一下 xor.guid 绑定的 guid 是需要手动编辑的吗？还是说 PuerTS 生成时会自动生成？我现在只看到代码注释里面有提醒，不要手动修改该段代码

**Comment by throw-out** [comment]
运行ts分析服务后xor.guid将会自动生成:
你可以手动开启`Tools/XOR/Servies/Start`菜单来启动服务, 或者在使用TsComponent相关功能时会弹窗提示是否立即启动

xor.guid的生成需要满足以下条件:
![image](https://github.com/user-attachments/assets/9e0702a1-fa76-4280-96a3-18a4f740a38b)

**Comment by Ricardo2001ZG** [comment]
> 运行ts分析服务后xor.guid将会自动生成: 你可以手动开启`Tools/XOR/Servies/Start`菜单来启动服务, 或者在使用TsComponent相关功能时会弹窗提示是否立即启动
> 
> xor.guid的生成需要满足以下条件: ![image](https://private-user-images.githubusercontent.com/45587825/360432465-9e0702a1-fa76-4280-96a3-18a4f740a38b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzEwMjksIm5iZiI6MTcyNDMzMDcyOSwicGF0aCI6Ii80NTU4NzgyNS8zNjA0MzI0NjUtOWUwNzAyYTEtZmE3Ni00MjgwLTk2YTMtMThhNGY3NDBhMzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEyNDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZjRhMjY4NzEwZmFkMDlhMTUzYjU4ZDU4MjNmNmMwNDNhOGZmMTgzZTg2N2M3ZmI2MmYxYWQ5MzRhYWUxMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fH0-7s0mSYy7VfxYouZz9n-oD1A_rKY3W4eGieFspcE)

好的谢谢，那我暂时没有问题了

**Comment by Ricardo2001ZG** [comment]
#13 该问题仍然存在，且与本问题相关

**Comment by throw-out** [comment]
#13提到的问题确实存在, 非常抱歉我忽略了它, 稍后我将提交一个修复.

信息面板显示UNKNOWN, 则表示未能获取到ts的类型元数据. 你需要点击`启动服务`或执行菜单`Tools/XOR/Services/Start`来启动ts分析服务.

至于你上述描述的Editor环境下无法加载Runtime/Resources目录下载的TextAsset文件, 我未能在Unity 2022.3.17上复现, 能否提供更多信息给我

**Comment by Ricardo2001ZG** [comment]
> #13 提到的问题确实存在, 非常抱歉我忽略了它, 稍后我将提交一个修复.
> 
> 信息面板显示UNKNOWN, 则表示未能获取到ts的类型元数据. 你需要点击`启动服务`或执行菜单`Tools/XOR/Services/Start`来启动ts分析服务.
> 
> 至于你上述描述的Editor环境下无法加载Runtime/Resources目录下载的TextAsset文件, 我未能在Unity 2022.3.17上复现, 能否提供更多信息给我

感谢您的回复，关于 UNKNOWN 的问题，在拷贝 xor 相关的 listener.mjs 以后，分析服务是可以正常启动的

listener.mjs 加载的问题稍后附上详细报告

**Comment by Ricardo2001ZG** [comment]
> #13 提到的问题确实存在, 非常抱歉我忽略了它, 稍后我将提交一个修复.
> 
> 信息面板显示UNKNOWN, 则表示未能获取到ts的类型元数据. 你需要点击`启动服务`或执行菜单`Tools/XOR/Services/Start`来启动ts分析服务.
> 
> 至于你上述描述的Editor环境下无法加载Runtime/Resources目录下载的TextAsset文件, 我未能在Unity 2022.3.17上复现, 能否提供更多信息给我

partial 的修复已生效，辛苦。

我猜测可能是因为重名文件的 partial 无法识别，不是说这个关键字本身的合并有问题，我检查了 puerts.unity.kit.xor 的引用，是正常的。

![20240824172641](https://github.com/user-attachments/assets/58b0fbf3-e061-4d49-a37e-2346e2cdc891)

在 Editor 环境下，直接运行项目时，会提示 puerts/xor/listener.mjs 这个文件 Module missing，同时附带很多异常信息

![20240824172858](https://github.com/user-attachments/assets/0edac6a6-eaba-44a4-b146-c26f0675d25a)

![20240824172917](https://github.com/user-attachments/assets/e7d19a4f-b1e7-4e85-ae6e-86a4b555b64d)

这个 mjs 实际的生成路径是 XOR\Runtime\Resources\puerts\xor\listener.mjs，在 XOR\Editor\Resources\puerts 路径下仅存在 xor-editor 文件夹，且里面不含 listener.mjs

按照我的理解，Editor 环境下只调用 Editor 路径下的 js 脚本，Runtime 的实机环境只调用 Runtime 路径的，是没有问题的。但是现在出现了 Editor 环境调用了 Runtime 的脚本，且附带了很多错误信息。

请问这个情况是预期设计吗？Editor 环境需要这个 listener 做 TsComponent 相关的一些监听和刷新操作吗？

**Comment by Ricardo2001ZG** [comment]
![20240826130407](https://github.com/user-attachments/assets/3e817b77-ca39-42f8-a3c0-38e214522083)

![20240826130418](https://github.com/user-attachments/assets/27bfaa20-4f72-41ba-b93e-3411df0d2b4e)

我在加载 XOR 模块的代码段添加了两个调试语句，在 Editor 中仅启动 ts 分析服务是正常的，但是直接在 Editor 中运行游戏时会报错，结合上面的信息和代码来看，不太确定是不是某些地方加载完文件后自动 gc 了这些文件，因为我看 loader 里面是有一些预读写操作的，会把很多文件先读进来

**Comment by Ricardo2001ZG** [comment]
今天我给 loader 的 dispose 函数添加了调试语句，想检查一下 loader 的释放顺序，看无法加载模块的问题是否是由 loader 引起的

经过测试，在 Editor 中启动 ts 分析线程后，直接点击运行，会将 worker 线程终止，随后 MixerLoader 的 Dispose 函数被调用，输出了警告语句

![20240827161022](https://github.com/user-attachments/assets/1287bc2e-d4d4-48b8-b470-e0134defcaf4)

这个问题的复现方式是：先在 Sample01 场景中启动 ts 分析线程，随后点击 Editor 的启动按钮运行场景

在这种情况下，运行场景会返回 Error，且报告无法加载模块

临时解决方法是：先运行场景，再启动分析线程读取相关信息

这个问题本身不是大问题，但是我还是建议更新 README 说明，临时提示该问题。这会给使用者带来一定的误解，认为程序本身有 bug，影响使用

完整修复要看能不能给 Loader 添加相关检测，以及对上述操作情况做一些代码检测，如果有什么建议思路欢迎详细讨论一下，有时间我再提一个 pr 修一下

**Comment by throw-out** [comment]
已定位到出问题的地方了, 在进入Playing模式时[InitializeOnLoad]的调用时机过早(如下图), 此时Resources.Load接口无法正确的加载资源:

![image](https://github.com/user-attachments/assets/2d54b386-8d2a-4b0d-aaa7-746493c94efa)

已尝试过线程延迟调用, 但无法解决问题; 

考虑的后续解决方案是, 完成[ts_metadata_cache](https://github.com/throw-out/puerts-unity-kit/tree/ts_metadata_cache)功能后, 进入Playing模式时不自动启动ts分析服务
