### ISSUE TITLE
ECMAScript(*.mts) can not import CS.*

### ISSUE THREAD

**Issue by Ricardo2001ZG** [throw-out/puerts-unity-kit#19]
请问使用项目中的 ECMAScript 生成 ESM 模块后，如何配置 tsconfig.json 以通过 'csharp.UnityEngine' 的形式导入模块？

目前已生成 modules 目录，但不清楚如何配置 json 使其通用于 commonjs 与 esm 模式，暂时是通过相对路径引用的

**Comment by throw-out** [comment]
dts声明文件默认生成路径为: `Assets/Gen/Typing/csharp/namespaces.d.ts`
js文件默认生成路径为: `Assets/Gen/Resources/puerts/modules/`

tscofnig.json配置引用此目录即可(下图为本仓库的配置)
![image](https://github.com/user-attachments/assets/5ffada10-5e12-49e0-8101-e44ee9909d17)

runtime加载js文件可参考以下Loader实现
`projects/Assets/Samples/Tools/ECMAScript/ECMAScriptLoader.cs`

**Comment by throw-out** [comment]
如果使用commonjs模块的话, 可以使用纯js代码实现以命名空间作为模块使用. 而esm模块需要为每一个类型生成`export xxx`语句才能正确执行, 因此需要预先生成js文件.

更多信息可以查看[此discussion](https://github.com/Tencent/puerts/discussions/821)

**Comment by Ricardo2001ZG** [comment]
> 如果使用commonjs模块的话, 可以使用纯js代码实现以命名空间作为模块使用. 而esm模块需要为每一个类型生成`export xxx`语句才能正确执行, 因此需要预先生成js文件.
> 
> 更多信息可以查看[此discussion](https://github.com/Tencent/puerts/discussions/821)

目前我是已经将这个路径修改为生成后的 puerts/modules 文件夹了，但是仍然在 vscode 中不识别，我不太清楚像 vscode 里本身的问题还是我的 tsconfig 配置不对，且没有做手动导出，我目前是想在自己的项目中规范使用 esm 的，尽量少使用 commonjs

**Comment by Ricardo2001ZG** [comment]
请问是否方便加个联系方式讨论？感觉项目还有很多地方可以完善一下，我的邮箱是 miao@ricardo2001zg.moe

**Comment by throw-out** [comment]
乐意之至, 我的邮箱是throw.out@qq.com, 或者你可以直接使用qq`1358620812`与我联系

**Comment by Ricardo2001ZG** [comment]
![2DD5A56D4D02846153009A8180CBAFED](https://github.com/user-attachments/assets/08ffb2d1-0097-4016-a4dd-93d54bc9bbfc)

经过调试，我现在确认是 tsconfig.json 的配置问题，现有库里的文件忽略了 mts 与 mjs 文件，会导致 mts 文件在 src 的子目录下是无法被编译配置识别的，也就导致 vscode 无法进行提示跳转

但是因为原配置文件里的 "./src/*"，又导致 src 根目录下所有类型的 ts 或 js 文件能被编译

临时修复办法是在配置文件中手动添加 "./src/**/*.mts" 与 "./src/**/*.mjs"，后续我会提一个 pr 修复这个问题
