### ISSUE TITLE
hot-reload 能支持adnroid和ios吗?

### ISSUE THREAD

**Issue by mingxxming** [throw-out/puerts-unity-kit#4]

**Comment by throw-out** [comment]
这取决于目标平台是否开启调试, puerts默认的iOS丶Android平台是不支持调试模块. 你需要自行编译带调试模块(inspector)的plugins然后打包.

[《Puerts Inspector指南（一）在UE4和Unity里调试Javascript》](https://zhuanlan.zhihu.com/p/359598262)一文第六节中说明了如何开启手机调试

**Comment by throw-out** [comment]
你可以查看这里的[[Unity] Plugin编译指南](https://github.com/Tencent/puerts/wiki/%5BUnity%5D-Plugin%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97#puerts-%E6%9C%AC%E8%BA%AB%E6%98%AF%E6%80%8E%E4%B9%88%E7%BC%96%E8%AF%91-c-plugin-%E7%9A%84)

**Comment by mingxxming** [comment]
好的，感谢~
